Administrativni dio/Controllers/HomeApartmaniController.cs
using Administrativni_dio.Models;
using Administrativni_dio.Repositories.Apartment;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Administrativni_dio.Controllers
{
    public class HomeApartmaniController : Controller
    {
        IApartmentRepository apartmentRepository = new ApartmentRepository();
        bool filtrirano = false;
        // GET: HomeApartmani
        public ActionResult Index()
        {
            if (Request.Cookies["UserSettings"] != null)
            {
                var cookie = Request.Cookies["UserSettings"];
                var filtriranaISortiranaListaApartmana = FiltrirajISortiraj(cookie["Rooms"], cookie["MaxAdults"], cookie["MaxChildren"], cookie["City"], cookie["Sort"]);
                var model = new SearchModel();
                model.Apartmani = filtriranaISortiranaListaApartmana;
                foreach (var apartman in model.Apartmani)
                {
                    apartman.PutanjaSlike = GenerirajPutanjuSlike();
                }
                return View(model);
            }

            if (filtrirano)
            {
                return View();
            }
            var searchModel = new SearchModel();
            searchModel.Apartmani = apartmentRepository.SelectApartments();
            foreach (var apartman in searchModel.Apartmani)
            {
                apartman.PutanjaSlike = GenerirajPutanjuSlike();
            }
            return View(searchModel);
        }

        [HttpGet]
        public ActionResult LogOff()
        {
            Session.Clear();
            if (Request.Cookies["UserSettings"] != null)
            {
                Response.Cookies["UserSettings"].Expires = DateTime.Now.AddDays(-1);
            }
            return Redirect("~/LoginForm.aspx");
        }

        [HttpPost]
        public ActionResult Filtriraj(string Rooms = null, string MaxAdults = null, string MaxChildren = null, string City = null, string Sort = null)
        {
            HttpCookie myCookie = new HttpCookie("UserSettings");
            myCookie["MaxAdults"] = MaxAdults;
            myCookie["MaxChildren"] = MaxChildren;
            myCookie["Rooms"] = Rooms;
            myCookie["City"] = City;
            myCookie["Sort"] = Sort;
            myCookie.Expires = DateTime.Now.AddDays(1);
            Response.SetCookie(myCookie);

            filtrirano = true;
            var model = new SearchModel();
            model.Apartmani = FiltrirajISortiraj(Rooms, MaxAdults, MaxChildren, City, Sort);
            foreach (var apartman in model.Apartmani)
            {
                apartman.PutanjaSlike = GenerirajPutanjuSlike();
            }
            return View("Index", model);
        }

        public List<Apartment> FiltrirajISortiraj(string Rooms = null, string MaxAdults = null, string MaxChildren = null, string City = null, string Sort = null)
        {
            List<Apartment> listaApartmana = new List<Apartment>();

            List<Apartment> tempApartmani = new List<Apartment>();
            tempApartmani = apartmentRepository.SelectApartments();

            if (!string.IsNullOrEmpty(Rooms))
            {
                try
                {
                    int numberOfRooms = int.Parse(Rooms);
                    var apartmentWithRooms = tempApartmani.Where(x => x.TotalRooms == numberOfRooms).ToList();
                    foreach (var apartment in apartmentWithRooms)
                    {
                        listaApartmana.Add(apartment);
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                    throw;
                }
            }

            if (!string.IsNullOrEmpty(MaxAdults))
            {
                try
                {
                    int maxAdults = int.Parse(MaxAdults);
                    var apartmentWithAdults = tempApartmani.Where(x => x.MaxAdults == maxAdults).ToList();
                    foreach (var apartment in apartmentWithAdults)
                    {
                        listaApartmana.Add(apartment);
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                    throw;
                }
            }

            if (!string.IsNullOrEmpty(MaxChildren))
            {
                try
                {
                    int maxChildren = int.Parse(MaxChildren);
                    var apartmentWithChildren = tempApartmani.Where(x => x.MaxChildren == maxChildren).ToList();
                    foreach (var apartment in apartmentWithChildren)
                    {
                        listaApartmana.Add(apartment);
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                    throw;
                }
            }

            if (!string.IsNullOrEmpty(City))
            {
                try
                {
                    var apartmentsInCity = tempApartmani.Where(x => x.City == City).ToList();
                    foreach (var apartment in apartmentsInCity)
                    {
                        listaApartmana.Add(apartment);
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                    throw;
                }
            }

            if (!string.IsNullOrEmpty(Sort))
            {
                int sortValue = int.Parse(Sort);
                switch (sortValue)
                {
                    case 0:
                        break;
                    case 1:
                        tempApartmani = tempApartmani.OrderBy(x => x.Price).ToList();
                        listaApartmana = listaApartmana.OrderBy(x => x.Price).ToList();
                        break;
                    case 2:
                        tempApartmani = tempApartmani.OrderByDescending(x => x.Price).ToList();
                        listaApartmana = listaApartmana.OrderByDescending(x => x.Price).ToList();
                        break;
                    default:
                        break;
                }
            }

            return (MaxAdults == "" && MaxChildren == "" && City == "" && Rooms == "") ? tempApartmani : listaApartmana;
        }

        public string GenerirajPutanjuSlike()
        {
            Random rnd = new Random(Guid.NewGuid().GetHashCode());
            return "/Images/slika" + rnd.Next(1, 8).ToString() + ".jpg";
        }
    }
}

Administrativni dio/Views/HomeApartmani/Index.cshtml
@model Administrativni_dio.Models.SearchModel
@{
    ViewBag.Title = "Home";
    ViewBag.Name = Session["Username"] ?? "random person";
    ViewBag.Visible = Session["Username"] == null ? "invisible" : "visible";
}

<div class="jumbotron mx-auto justify-content-center mb-5">
    <h1 class="display-4">Filtriranje i sortiranje</h1>
    @using (Html.BeginForm("Filtriraj", "HomeApartmani", FormMethod.Post))
    {<div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Max Odraslih</span>
            </div>
            <input type="text" class="form-control" placeholder="Max Odraslih" name="MaxAdults" id="MaxAdults">
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Max Djece</span>
            </div>
            <input type="text" class="form-control" placeholder="Max Djece" name="MaxChildren" id="MaxChildren">
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Sobe</span>
            </div>
            <input type="text" class="form-control" placeholder="Sobe" name="Rooms" id="Rooms">
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Grad</span>
            </div>
            <input type="text" class="form-control" placeholder="Grad" name="City" id="City">
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Sortiranje po cijeni</span>
            </div>
            @Html.DropDownListFor(
           model => model.Sort,
           new SelectList(
                  new List<Object>{
                       new { value = 0 , text = "Normalno"  },
                       new { value = 1 , text = "Najjeftinije prvo" },
                       new { value = 2 , text = "Najskuplje prvo"}
                    },
                  "value",
                  "text",
                  Model.Sort
           )
        )
        </div>
        <button type="submit" class="btn-success">Filter</button>
    }
</div>


<div class="justify-content-center">
    <div class="row row-cols-1 row-cols-md-2 g-4 justify-content-center">

        @if (Model != null)
        {
            int a = 0;
            foreach (var item in Model.Apartmani)
            {
                if (a % 2 == 0)
                {
                    <div class="col justify-content-center mx-auto">

                        <div class="card justify-content-center mx-auto">

                            <img src="@item.PutanjaSlike" alt="Card image cap">
                            <div class="card-body">
                                <h5 class="card-title">
                                    @item.ApartmentName
                                    @if (item.ApartmentStatus == "Slobodno")
                                    {
                                        <p class="text-success">@item.ApartmentStatus</p>
                                    }
                                    @if (item.ApartmentStatus == "Zauzeto")
                                    {
                                        <p class="text-danger">@item.ApartmentStatus</p>
                                    }
                                    @if (item.ApartmentStatus == "Rezervirano")
                                    {
                                        <p class="text-warning">@item.ApartmentStatus</p>
                                    }
                                </h5>
                                <p class="card-text">City: @item.City</p>
                                <p class="card-text">Price: @item.Price</p>
                                @using (Html.BeginForm("Index", "DetaljiApartmana", FormMethod.Post))
                                {
                                    <input type="hidden" class="form-control" value="@item.IDApartment" name="IdApartman" id="IdApartman">
                                    <button class="btn btn-primary" type="submit">Detalji</button>
                                }

                            </div>
                        </div>
                    </div>
                }
            }
        }
    </div>
</div>